import { execFile } from "node:child_process";
import { lstat, mkdir, readFile, readdir, realpath, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { promisify } from "node:util";
import { buildProject } from "./build.js";

const execFileAsync = promisify(execFile);

export const GITHUB_PAGES_WORKFLOW = ".github/workflows/site-pages.yml";
const MANAGED_MARKER = "# Generated by Site Spec v0.1 for GitHub Pages.";
const MAX_ARTIFACT_BYTES = 10 * 1024 * 1024 * 1024;

export interface GitHubRepository {
  owner: string;
  repo: string;
  remote: string;
  remoteUrl: string;
}

export interface GitHubPagesDeployOptions {
  root: string;
  remote?: string;
  branch?: string;
}

export interface GitHubPagesDeployResult {
  success: true;
  provider: "github-pages";
  repository: string;
  branch: string;
  siteUrl: string;
  expectedGitHubPagesUrl: string;
  customDomain: boolean;
  workflowFile: string;
  workflowChanged: boolean;
  artifactBytes: number;
  pages: string[];
  next: "commit-and-push";
  notes: string[];
}

export class GitHubPagesDeployError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly details?: Record<string, unknown>
  ) {
    super(message);
    this.name = "GitHubPagesDeployError";
  }
}

async function git(root: string, args: string[]): Promise<string> {
  try {
    const result = await execFileAsync("git", ["-C", root, ...args], { encoding: "utf8" });
    return result.stdout.trim();
  } catch (error) {
    const stderr = typeof error === "object" && error && "stderr" in error ? String((error as { stderr?: unknown }).stderr ?? "").trim() : "";
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_GIT_FAILED",
      stderr || (error instanceof Error ? error.message : String(error)),
      { args }
    );
  }
}

function parseGitHubRemote(remoteUrl: string, remote: string): GitHubRepository {
  const patterns = [
    /^git@github\.com:([^/]+)\/(.+?)(?:\.git)?$/i,
    /^ssh:\/\/git@github\.com\/([^/]+)\/(.+?)(?:\.git)?\/?$/i,
    /^https?:\/\/github\.com\/([^/]+)\/(.+?)(?:\.git)?\/?$/i,
    /^git:\/\/github\.com\/([^/]+)\/(.+?)(?:\.git)?\/?$/i
  ];
  for (const pattern of patterns) {
    const match = remoteUrl.match(pattern);
    if (!match) continue;
    const owner = match[1]!;
    const repo = match[2]!.replace(/\.git$/i, "");
    if (owner && repo && !repo.includes("/")) return { owner, repo, remote, remoteUrl };
  }
  throw new GitHubPagesDeployError(
    "GITHUB_PAGES_REMOTE_UNSUPPORTED",
    `Remote ${JSON.stringify(remote)} is not a supported github.com repository URL: ${remoteUrl}`
  );
}

export function expectedGitHubPagesUrl(owner: string, repo: string): string {
  const host = `${owner}.github.io`;
  return repo.toLowerCase() === host.toLowerCase()
    ? `https://${host}`
    : `https://${host}/${repo}`;
}

function normalizeComparableUrl(value: string): string {
  const url = new URL(value);
  url.hash = "";
  url.search = "";
  url.hostname = url.hostname.toLowerCase();
  if (url.pathname !== "/") url.pathname = url.pathname.replace(/\/+$/, "");
  return url.toString().replace(/\/$/, "");
}

function validateSiteUrl(siteUrl: string, repository: GitHubRepository): { customDomain: boolean; expected: string; notes: string[] } {
  let url: URL;
  try {
    url = new URL(siteUrl);
  } catch {
    throw new GitHubPagesDeployError("GITHUB_PAGES_SITE_URL_INVALID", `Invalid site.url: ${siteUrl}`);
  }
  if (url.protocol !== "https:") {
    throw new GitHubPagesDeployError("GITHUB_PAGES_SITE_URL_HTTPS_REQUIRED", "GitHub Pages production site.url must use https://.");
  }
  const reserved = [".test", ".invalid", ".localhost", ".example"];
  if (url.hostname === "localhost" || reserved.some(suffix => url.hostname.endsWith(suffix))) {
    const expected = expectedGitHubPagesUrl(repository.owner, repository.repo);
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_SITE_URL_NOT_PUBLIC",
      `site.url ${JSON.stringify(siteUrl)} is not a public production URL. For this repository, use ${expected} or configure a custom domain.`,
      { expectedSiteUrl: expected }
    );
  }

  const expected = expectedGitHubPagesUrl(repository.owner, repository.repo);
  const githubHost = `${repository.owner}.github.io`.toLowerCase();
  if (url.hostname.toLowerCase() === githubHost) {
    if (normalizeComparableUrl(siteUrl).toLowerCase() !== normalizeComparableUrl(expected).toLowerCase()) {
      throw new GitHubPagesDeployError(
        "GITHUB_PAGES_SITE_URL_MISMATCH",
        `site.url is ${siteUrl}, but repository ${repository.owner}/${repository.repo} is served at ${expected}.`,
        { expectedSiteUrl: expected }
      );
    }
    return { customDomain: false, expected, notes: [] };
  }

  return {
    customDomain: true,
    expected,
    notes: [
      `site.url uses custom domain ${url.hostname}. Configure that domain in GitHub repository Settings > Pages; a CNAME file alone does not configure it.`
    ]
  };
}

async function discoverRepository(root: string, remote: string): Promise<GitHubRepository> {
  let gitRoot: string;
  try {
    gitRoot = await git(root, ["rev-parse", "--show-toplevel"]);
  } catch (error) {
    if (error instanceof GitHubPagesDeployError) {
      throw new GitHubPagesDeployError("GITHUB_PAGES_GIT_REPOSITORY_REQUIRED", "npm run site -- deploy github-pages requires the Site Spec project root to be a Git repository.");
    }
    throw error;
  }
  const projectRoot = await realpath(root);
  const repositoryRoot = await realpath(gitRoot);
  if (projectRoot !== repositoryRoot) {
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_PROJECT_ROOT_REQUIRED",
      "Site Spec v0.1 GitHub Pages deployment requires the Site Spec project root to equal the Git repository root.",
      { projectRoot, repositoryRoot }
    );
  }

  let remoteUrl: string;
  try {
    remoteUrl = await git(root, ["remote", "get-url", remote]);
  } catch {
    throw new GitHubPagesDeployError("GITHUB_PAGES_REMOTE_MISSING", `Git remote ${JSON.stringify(remote)} was not found.`);
  }
  return parseGitHubRemote(remoteUrl, remote);
}

async function resolveBranch(root: string, remote: string, explicit?: string): Promise<string> {
  let branch = explicit?.trim();
  if (!branch) {
    try {
      const symbolic = await git(root, ["symbolic-ref", "--quiet", "--short", `refs/remotes/${remote}/HEAD`]);
      branch = symbolic.replace(new RegExp(`^${remote.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/`), "");
    } catch {
      try {
        const current = await git(root, ["branch", "--show-current"]);
        if (current === "main" || current === "master") branch = current;
        else if (current) {
          throw new GitHubPagesDeployError(
            "GITHUB_PAGES_BRANCH_UNRESOLVED",
            `Could not determine ${remote}'s default branch while current branch is ${JSON.stringify(current)}. Pass --branch explicitly.`
          );
        }
      } catch (error) {
        if (error instanceof GitHubPagesDeployError && error.code === "GITHUB_PAGES_BRANCH_UNRESOLVED") throw error;
        branch = "";
      }
    }
  }
  if (!branch) branch = "main";
  try {
    await git(root, ["check-ref-format", "--branch", branch]);
  } catch {
    throw new GitHubPagesDeployError("GITHUB_PAGES_BRANCH_INVALID", `Invalid deployment branch: ${branch}`);
  }
  return branch;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}


async function validateProjectPackaging(root: string): Promise<void> {
  let packageJson: { scripts?: Record<string, string>; devDependencies?: Record<string, string> };
  try {
    packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8")) as typeof packageJson;
  } catch {
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_PACKAGE_JSON_REQUIRED",
      "GitHub Pages deployment requires the Site Spec site's package.json."
    );
  }

  if (!packageJson.scripts?.build) {
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_BUILD_SCRIPT_REQUIRED",
      "package.json must define a build script. Generated Site Spec sites use: \"build\": \"sitespec build\"."
    );
  }

  const cliVersion = packageJson.devDependencies?.["@sitespec/cli"];
  if (!cliVersion || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(cliVersion)) {
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_PINNED_CLI_REQUIRED",
      "package.json must pin @sitespec/cli to an exact version so local development and CI use the same engine."
    );
  }

  try {
    JSON.parse(await readFile(join(root, "package-lock.json"), "utf8"));
  } catch {
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_PACKAGE_LOCK_REQUIRED",
      "GitHub Pages deployment uses npm ci. Run npm install and commit package-lock.json before deploying."
    );
  }
}

export function githubPagesWorkflow(branch: string): string {
  return `${MANAGED_MARKER}
name: Deploy Site Spec to GitHub Pages

on:
  push:
    branches:
      - ${yamlString(branch)}
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Site Spec
        run: npm run build

      - name: Verify GitHub Pages URL
        env:
          GITHUB_PAGES_BASE_URL: \${{ steps.pages.outputs.base_url }}
        run: |
          node --input-type=module <<'NODE'
          import { readFileSync } from "node:fs";
          const resolved = JSON.parse(readFileSync(".site/resolved.json", "utf8"));
          const normalize = (value) => {
            const url = new URL(value);
            url.hash = "";
            url.search = "";
            if (url.pathname !== "/") url.pathname = url.pathname.replace(/\\/+$/, "");
            url.hostname = url.hostname.toLowerCase();
            return url.toString().replace(/\\/$/, "");
          };
          if (normalize(resolved.site.url) !== normalize(process.env.GITHUB_PAGES_BASE_URL)) {
            console.error("Site Spec site.url (" + resolved.site.url + ") does not match GitHub Pages (" + process.env.GITHUB_PAGES_BASE_URL + ").");
            console.error("Update site.yaml or configure the intended custom domain in Settings > Pages.");
            process.exit(1);
          }
          NODE

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;
}

async function writeManagedWorkflow(root: string, branch: string): Promise<{ file: string; changed: boolean }> {
  const file = join(root, GITHUB_PAGES_WORKFLOW);
  const desired = githubPagesWorkflow(branch);
  let current: string | undefined;
  try {
    current = await readFile(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  if (current === desired) return { file: GITHUB_PAGES_WORKFLOW, changed: false };
  if (current !== undefined && !current.startsWith(MANAGED_MARKER)) {
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_WORKFLOW_CONFLICT",
      `${GITHUB_PAGES_WORKFLOW} already exists and is not managed by Site Spec. Refusing to overwrite it.`
    );
  }
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, desired, "utf8");
  return { file: GITHUB_PAGES_WORKFLOW, changed: true };
}

async function validateArtifactDirectory(outDir: string): Promise<number> {
  let total = 0;
  async function walk(path: string): Promise<void> {
    const info = await lstat(path);
    if (info.isSymbolicLink()) {
      throw new GitHubPagesDeployError("GITHUB_PAGES_ARTIFACT_SYMLINK", `GitHub Pages artifacts may not contain symbolic links: ${relative(outDir, path)}`);
    }
    if (info.isFile()) {
      if (info.nlink > 1) {
        throw new GitHubPagesDeployError("GITHUB_PAGES_ARTIFACT_HARDLINK", `GitHub Pages artifacts may not contain hard links: ${relative(outDir, path)}`);
      }
      total += info.size;
      if (total > MAX_ARTIFACT_BYTES) {
        throw new GitHubPagesDeployError("GITHUB_PAGES_ARTIFACT_TOO_LARGE", "GitHub Pages artifact exceeds the 10 GB limit.");
      }
      return;
    }
    if (!info.isDirectory()) return;
    const entries = await readdir(path);
    entries.sort((a, b) => a.localeCompare(b));
    for (const entry of entries) await walk(join(path, entry));
  }
  await walk(outDir);
  return total;
}

export async function deployGitHubPages(options: GitHubPagesDeployOptions): Promise<GitHubPagesDeployResult> {
  const root = resolve(options.root);
  const remote = options.remote ?? "origin";
  const repository = await discoverRepository(root, remote);
  const branch = await resolveBranch(root, remote, options.branch);
  await validateProjectPackaging(root);

  const built = await buildProject(root);
  if (!built.success) {
    const summary = built.diagnostics
      .filter(diagnostic => diagnostic.severity === "error")
      .map(diagnostic => {
        const where = [diagnostic.file, diagnostic.page, diagnostic.section]
          .filter(Boolean)
          .join(":");
        return `${diagnostic.code}${where ? ` (${where})` : ""}: ${diagnostic.message}`;
      })
      .join("\n");
    throw new GitHubPagesDeployError(
      "GITHUB_PAGES_BUILD_FAILED",
      `Production build failed; GitHub Pages workflow was not changed.${summary ? `\n${summary}` : ""}`,
      { diagnostics: built.diagnostics }
    );
  }

  const resolvedSite = JSON.parse(await readFile(join(root, ".site", "resolved.json"), "utf8")) as { site?: { url?: string } };
  const siteUrl = resolvedSite.site?.url;
  if (!siteUrl) throw new GitHubPagesDeployError("GITHUB_PAGES_SITE_URL_INVALID", "Resolved site has no production URL.");
  const urlCheck = validateSiteUrl(siteUrl, repository);

  const artifactBytes = await validateArtifactDirectory(join(root, "dist"));
  const workflow = await writeManagedWorkflow(root, branch);

  return {
    success: true,
    provider: "github-pages",
    repository: `${repository.owner}/${repository.repo}`,
    branch,
    siteUrl,
    expectedGitHubPagesUrl: urlCheck.expected,
    customDomain: urlCheck.customDomain,
    workflowFile: workflow.file,
    workflowChanged: workflow.changed,
    artifactBytes,
    pages: built.pages,
    next: "commit-and-push",
    notes: [
      ...urlCheck.notes,
      "GitHub Pages must use GitHub Actions as its publishing source. Configure it once in repository Settings > Pages if it is not enabled yet.",
      `Commit and push ${workflow.file}; pushes to ${branch} will build and deploy dist/ through GitHub Actions.`
    ]
  };
}
